export const CHANGE_HOME_DATA = 'change_home_data'
export const ADD_HOME_LIST = 'add_home_list'
export const TOGGLE_SCROLL_TOP = 'toggle_scroll_top'
export const CHANGE_OVERIMG = 'change_ImgOver'
export const CHANGE_OUTIMG = 'change_ImgOut'